name = Doom One

kitty     = Doom One
gtk       = Orchis-Dark
icons     = Colloid-Dark
wallpaper = wallhaven-d8633m_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #282c34
bg_alt    = #3f444a
fg        = #bbc2cf
primary   = #ecbe7b
secondary = #51afef
disabled  = #5b6268
alert     = #da8548
