name = Monokai

kitty   = Monokai
gtk       = Orchis-Pink-Dark
icons     = Colloid-Dark
wallpaper = wallhaven-3q9vmd_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #272822
bg_alt    = #3e3d32
fg        = #f8f8f2
primary   = #f92672
secondary = #66d9ef
disabled  = #75715e
alert     = #fd971f
