name = Gruvbox

kitty     = Gruvbox Dark
gtk       = Orchis-Orange-Dark
icons     = Colloid-Gruvbox-Dark
wallpaper = gruvbox-dark-debian-scalable.svg

# Waybar / rofi / swaync palette
bg        = #282828
bg_alt    = #3c3836
fg        = #ebdbb2
primary   = #d79921
secondary = #458588
disabled  = #928374
alert     = #cc241d
