name = GitHub Dark

kitty   = GitHub Dark
gtk       = Orchis-Grey-Dark
icons     = Colloid-Grey-Dracula-Dark
wallpaper = wallhaven-218x7m_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #0d1117
bg_alt    = #2f363d
fg        = #d0d7de
primary   = #d29922
secondary = #b3e5fc
disabled  = #4e5b55
alert     = #D29922
