name = Catppuccin

kitty   = Catppuccin-Mocha
gtk       = Orchis-Purple-Dark
icons     = Colloid-Catppuccin-Dark
wallpaper = wallhaven-d61z1m_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #232634
bg_alt    = #51576d
fg        = #c6d0f5
primary   = #ef9f76
secondary = #8caaee
disabled  = #a6d189
alert     = #e5c890
