name = Dracula

kitty     = Dracula
gtk       = Orchis-Purple-Dark-Dracula
icons     = Colloid-Dracula-Dark
wallpaper = dracula.webp

# Waybar / rofi / swaync palette
bg        = #282a36
bg_alt    = #44475a
fg        = #f8f8f2
primary   = #f1fa8c
secondary = #6272a4
disabled  = #44475a
alert     = #ffb86c
