name = Moonfly

kitty     = Moonfly
gtk       = Orchis-Dark
icons     = Colloid-Dark
wallpaper = wallhaven-x6gmxl_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #080808
bg_alt    = #323437
fg        = #b2b2b2
primary   = #e3c78a
secondary = #80a0ff
disabled  = #9e9e9e
alert     = #ef9f76
