name = Giants

gtk       = Breeze
icons     = Giants
kde       = Giants

bg        = #27241f
bg_alt    = #3d3a35
fg        = #E1D5C2
primary   = #97786d
secondary = #b28b7e
disabled  = #8a857a
alert     = #b3826a

wallpaper = slideshow
