name = Nord

kitty     = Nord
gtk       = Orchis-Dark-Nord
icons     = Colloid-Nord-Dark
wallpaper = wallhaven-6k1dj7_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #2e3440
bg_alt    = #3b4252
fg        = #d8dee9
primary   = #ebcb8b
secondary = #81a1c1
disabled  = #4c566a
alert     = #d08770
