name = Kanagawa

kitty   = Kanagawa
gtk       = Orchis-Orange-Dark
icons     = Colloid-Orange-Dark
wallpaper = wallhaven-jx9mzp_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #1F1F28
bg_alt    = #2A2A37
fg        = #DCD7BA
primary   = #ff9e3b
secondary = #7e9cd8
disabled  = #54546D
alert     = #ffa066
