name = Rose Pine Moon

kitty   = Rosé Pine Moon
gtk       = Orchis-Purple-Dark
icons     = Colloid-Catppuccin-Dark
wallpaper = wallhaven-85erok_3440x1440.png

# Waybar / rofi / swaync palette
bg        = #232136
bg_alt    = #2a273f
fg        = #e0def4
primary   = #f6c177
secondary = #c4a7e7
disabled  = #6e6a86
alert     = #eb6f92
